# Generated by Django 2.0.4 on 2018-04-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
