# Generated by Django 2.0.4 on 2018-06-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_submit',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
